// <auto-generated />
using System;
using API_Proyecto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Proyecto.Migrations
{
    [DbContext(typeof(ReservacionesDbContext))]
    partial class ReservacionesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Proyecto.Models.Comentario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocalID")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LocalID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("API_Proyecto.Models.Horario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("LocalID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LocalID");

                    b.ToTable("Horarios");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            HoraFin = new TimeSpan(0, 12, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 8, 0, 0, 0),
                            LocalID = 1
                        },
                        new
                        {
                            ID = 2,
                            HoraFin = new TimeSpan(0, 16, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 14, 0, 0, 0),
                            LocalID = 1
                        },
                        new
                        {
                            ID = 3,
                            HoraFin = new TimeSpan(0, 20, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 18, 0, 0, 0),
                            LocalID = 1
                        },
                        new
                        {
                            ID = 4,
                            HoraFin = new TimeSpan(0, 23, 59, 0, 0),
                            HoraInicio = new TimeSpan(0, 22, 0, 0, 0),
                            LocalID = 1
                        },
                        new
                        {
                            ID = 5,
                            HoraFin = new TimeSpan(0, 12, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 8, 0, 0, 0),
                            LocalID = 2
                        },
                        new
                        {
                            ID = 6,
                            HoraFin = new TimeSpan(0, 16, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 14, 0, 0, 0),
                            LocalID = 2
                        },
                        new
                        {
                            ID = 7,
                            HoraFin = new TimeSpan(0, 20, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 18, 0, 0, 0),
                            LocalID = 2
                        },
                        new
                        {
                            ID = 8,
                            HoraFin = new TimeSpan(0, 23, 59, 0, 0),
                            HoraInicio = new TimeSpan(0, 22, 0, 0, 0),
                            LocalID = 2
                        });
                });

            modelBuilder.Entity("API_Proyecto.Models.ImagenLocal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("LocalID")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LocalID");

                    b.ToTable("ImagenesLocal");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            LocalID = 1,
                            Url = "https://img10.naventcdn.com/avisos/resize/9/01/41/76/97/06/1200x1200/1130234069.jpg"
                        },
                        new
                        {
                            ID = 2,
                            LocalID = 1,
                            Url = "https://img10.naventcdn.com/avisos/resize/9/01/41/76/97/06/1200x1200/1130234070.jpg"
                        },
                        new
                        {
                            ID = 3,
                            LocalID = 1,
                            Url = "https://img10.naventcdn.com/avisos/resize/9/01/41/76/97/06/1200x1200/1130234071.jpg"
                        },
                        new
                        {
                            ID = 4,
                            LocalID = 2,
                            Url = "https://img10.naventcdn.com/avisos/resize/9/00/91/40/78/30/1200x1200/1121170509.jpg"
                        },
                        new
                        {
                            ID = 5,
                            LocalID = 2,
                            Url = "https://img10.naventcdn.com/avisos/resize/9/00/91/40/78/30/1200x1200/1121170504.jpg"
                        },
                        new
                        {
                            ID = 6,
                            LocalID = 2,
                            Url = "https://img10.naventcdn.com/avisos/resize/9/00/91/40/78/30/1200x1200/1121170505.jpg"
                        });
                });

            modelBuilder.Entity("API_Proyecto.Models.Local", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropietarioID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PropietarioID");

                    b.ToTable("Locales");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Capacidad = 50,
                            Descripcion = "Cafetería con ambiente acogedor y música en vivo.",
                            Direccion = "Avenida Siempre Viva 742",
                            Nombre = "Café Central",
                            PropietarioID = 1
                        },
                        new
                        {
                            ID = 2,
                            Capacidad = 20,
                            Descripcion = "Espacio cultural con selección de libros de autores independientes.",
                            Direccion = "Calle Literaria 101",
                            Nombre = "Librería Letras",
                            PropietarioID = 2
                        });
                });

            modelBuilder.Entity("API_Proyecto.Models.Reserva", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorarioID")
                        .HasColumnType("int");

                    b.Property<int>("LocalID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("HorarioID");

                    b.HasIndex("LocalID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("API_Proyecto.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            Nombre = "administrador",
                            Password = "2003",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "andrei@gmail.com",
                            Nombre = "andrei",
                            Password = "2003",
                            Username = "andrei"
                        });
                });

            modelBuilder.Entity("API_Proyecto.Models.Comentario", b =>
                {
                    b.HasOne("API_Proyecto.Models.Local", "Local")
                        .WithMany("Comentarios")
                        .HasForeignKey("LocalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Proyecto.Models.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API_Proyecto.Models.Horario", b =>
                {
                    b.HasOne("API_Proyecto.Models.Local", "Local")
                        .WithMany("Horarios")
                        .HasForeignKey("LocalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");
                });

            modelBuilder.Entity("API_Proyecto.Models.ImagenLocal", b =>
                {
                    b.HasOne("API_Proyecto.Models.Local", "Local")
                        .WithMany("Imagenes")
                        .HasForeignKey("LocalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");
                });

            modelBuilder.Entity("API_Proyecto.Models.Local", b =>
                {
                    b.HasOne("API_Proyecto.Models.Usuario", "Propietario")
                        .WithMany("Locales")
                        .HasForeignKey("PropietarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("API_Proyecto.Models.Reserva", b =>
                {
                    b.HasOne("API_Proyecto.Models.Horario", "Horario")
                        .WithMany()
                        .HasForeignKey("HorarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Proyecto.Models.Local", "Local")
                        .WithMany("Reservas")
                        .HasForeignKey("LocalID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("API_Proyecto.Models.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Horario");

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API_Proyecto.Models.Local", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Horarios");

                    b.Navigation("Imagenes");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("API_Proyecto.Models.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Locales");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
